version: "3"
services:
 db:
  image: postgres
  volumes:
   - ./pgdata:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
   POSTGRES_DB: nba 
  ports:
   - "5432:5432"
